[Service]
Environment="LUMII_HTTP_ACCESS_LOG_ENABLED=true"
Environment="LUMII_HTTP_ACCESS_LOG_INCLUDE_HEALTH=false"
Environment="LUMII_HTTP_ACCESS_LOG_SLOW_MS=2000"
StandardOutput=journal
StandardError=journal
SyslogIdentifier=lumii-backend
